# Generated by Django 3.2.1 on 2021-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('interest', models.CharField(max_length=20)),
            ],
        ),
    ]
